name: rust test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rust_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup OpenGemini
        uses: shoothzj/setup-opengemini-action@main
      - name: Run unit tests
        run: cargo test
